export const AUTH_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    UPDATE_PROFILE: 'UPDATE_PROFILE'
  };
  
  export const GIG_ACTIONS = {
    CHANGE_INPUT: 'CHANGE_INPUT',
    ADD_IMAGES: 'ADD_IMAGES',
    ADD_FEATURE: 'ADD_FEATURE',
    REMOVE_FEATURE: 'REMOVE_FEATURE',
    RESET_FORM: 'RESET_FORM',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    INIT_GIG: 'INIT_GIG',  
    UPDATE_GIG: 'UPDATE_GIG' 
  };
  
  
  export const ORDER_ACTIONS = {
    CREATE_ORDER: 'CREATE_ORDER',
    UPDATE_ORDER: 'UPDATE_ORDER',
    COMPLETE_ORDER: 'COMPLETE_ORDER',
    CANCEL_ORDER: 'CANCEL_ORDER'
  };
  